// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCefCrupPYBnFueDP3VCOktErpX0pfOr4w',
    appId: '1:838239470188:web:47d108284a96e8f45bce49',
    messagingSenderId: '838239470188',
    projectId: 'nyamgo-5d83c',
    authDomain: 'nyamgo-5d83c.firebaseapp.com',
    storageBucket: 'nyamgo-5d83c.firebasestorage.app',
    measurementId: 'G-52YD4Q9K0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBa-X5jq8nOJR5aByzivMvSL33DsOHLRU',
    appId: '1:838239470188:android:07a741f9c871053b5bce49',
    messagingSenderId: '838239470188',
    projectId: 'nyamgo-5d83c',
    storageBucket: 'nyamgo-5d83c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA4y4saNrzhEtYRd6c0mke_1EXk0TC-OA',
    appId: '1:838239470188:ios:1f574d6b7f285c645bce49',
    messagingSenderId: '838239470188',
    projectId: 'nyamgo-5d83c',
    storageBucket: 'nyamgo-5d83c.firebasestorage.app',
    iosBundleId: 'com.example.nyamgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA4y4saNrzhEtYRd6c0mke_1EXk0TC-OA',
    appId: '1:838239470188:ios:1f574d6b7f285c645bce49',
    messagingSenderId: '838239470188',
    projectId: 'nyamgo-5d83c',
    storageBucket: 'nyamgo-5d83c.firebasestorage.app',
    iosBundleId: 'com.example.nyamgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCefCrupPYBnFueDP3VCOktErpX0pfOr4w',
    appId: '1:838239470188:web:cc4d21b87e4d28e75bce49',
    messagingSenderId: '838239470188',
    projectId: 'nyamgo-5d83c',
    authDomain: 'nyamgo-5d83c.firebaseapp.com',
    storageBucket: 'nyamgo-5d83c.firebasestorage.app',
    measurementId: 'G-HJ7DZ2JXTN',
  );
}
